#!/bin/bash

clear
echo -e "================================================="
echo -e "#     Premium Auto Script By xRemiX        #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# Allah SWT                                     #"
echo -e "# My Family                                     #"
echo -e "# Tegar Prayuda                                 #"
echo -e "# Team Provider Exploit                         #"
echo -e "# Wildy Project                                 #"
echo -e "# Maintenancez                                  #"
echo -e "# Geo                                           #"
echo -e "# xRemiX                                   #"
echo -e "#-----------------------------------------------#"
echo -e "# Created By : xRemiX                      #"  
echo -e "# Contact : t.me/xRemiX                    #"
echo -e "================================================="
